env:
  es2021: true
  node: true
extends:
  # I want to know the best practices for the settings here.
  # I don't know it, but this so many extends are enough to make it feel non-exemplary.
  - plugin:markdown/recommended
  - plugin:yaml/recommended
  - plugin:editorconfig/noconflict
  - plugin:jsdoc/recommended
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - airbnb-typescript/base
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
plugins:
  - pug
parserOptions:
  ecmaFeatures:
    impliedStrict: true
  project: ./tsconfig.json
root: true
rules:
  '@typescript-eslint/consistent-type-imports': warn
  '@typescript-eslint/dot-notation': 'off'
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - '/gulpfile.?([cm])[jt]s'
        - '**/*.config.?([cm])[jt]s'
        - '**/*.stories.?([cm])[jt]s?(x)'
  import/order: warn
  jsdoc/require-param-type: 'off'
  jsdoc/require-returns-type: 'off'
  sort-imports:
    - warn
    - ignoreDeclarationSort: true
settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
    webpack:
      config: webpack.config.ts
