env:
  es6: true
  es2020: true
  node: true
extends:
  - eslint:recommended
  - airbnb-typescript/base
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier
  - prettier/@typescript-eslint
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  project: ./tsconfig.json
rules:
  '@typescript-eslint/no-unused-vars':
    - error
    - args: none
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - gulpfile.?s
        - '*.config.?s'
  no-console:
    - warn
settings:
  import/resolver:
    webpack:
      config: webpack.config.ts
